openapi: 3.0.0
info:
  title: SL Railway Application
  description: API documentation for SLRailway
  version: "1.0.0"

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
      description: Please insert valid API Key

servers:
  - description: SLRailway Development environment
    url: https://4iecw6fm2f.execute-api.ap-southeast-1.amazonaws.com/api

tags:
  - name: SL Railway

paths:
  /train/add:
    post:
      security:
        - ApiKeyAuth: []
      tags:
        - SL Railway
      summary: Add new train data
      responses:
        "201":
          description: Adds a new entry for train data, including location, speed, and timestamp.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: integer
                  message:
                    type: string

                  data:
                    type: object
                    properties:
                      trainId:
                        type: string
                        description: Unique identifier for the train
                      location:
                        type: array
                        items:
                          type: string
                          description: Array of location data (latitude, longitude)
                      speed:
                        type: string
                        description: Current speed of the train
                      timestamp:
                        type: string
                        description: Timestamp of the data

                example:
                  status_code: 201
                  message: success
                  data:
                    trainId: 1
                    location: [79.86600802064461, 6.95207031031493]
                    speed: 150
                    timestamp: "2024-08-31T14:05:40.984Z"

        "401":
          description: Unauthorized - Invalid API Key
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: integer
                  message:
                    type: string

                  data:
                    type: object
                    properties:
                      error_message:
                        type: string

                example:
                  status_code: 401
                  message: error
                  data:
                    error_message: Unauthorized - Invalid API Key

        "500":
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: integer
                  message:
                    type: string

                  data:
                    type: object
                    properties:
                      error_message:
                        type: string

                example:
                  status_code: 500
                  message: error
                  data:
                    error_message: Server error

      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - trainId
                - location
                - speed
              properties:
                trainId:
                  type: string
                location:
                  type: string
                speed:
                  type: string
                timestamp:
                  type: string

              example:
                trainId: 1
                location: [79.86600802064461, 6.95207031031493]
                speed: 150
                timestamp: "2024-08-31T14:05:40.984Z"

  /train/{trainId}:
    get:
      security:
        - ApiKeyAuth: []
      tags:
        - SL Railway
      summary: Get latest train data
      parameters:
        - in: path
          name: trainId
          schema:
            type: string
          required: true
          description: Numeric ID of the train to get train detail
      responses:
        "200":
          description: Retrieves the latest data entry for a specific train by trainId.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: integer
                  message:
                    type: string

                  data:
                    type: object
                    properties:
                      trainId:
                        type: string
                        description: Unique identifier for the train
                      location:
                        type: array
                        items:
                          type: string
                          description: Array of location data (latitude, longitude)
                      speed:
                        type: string
                        description: Current speed of the train
                      timestamp:
                        type: string
                        description: Timestamp of the data

                example:
                  status_code: 201
                  message: success
                  data:
                    trainId: 1
                    location: [79.86600802064461, 6.95207031031493]
                    speed: 150
                    timestamp: "2024-08-31T14:05:40.984Z"

        "401":
          description: Unauthorized - Invalid API Key
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: integer
                  message:
                    type: string

                  data:
                    type: object
                    properties:
                      error_message:
                        type: string

                example:
                  status_code: 401
                  message: error
                  data:
                    error_message: Unauthorized - Invalid API Key

        "500":
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: integer
                  message:
                    type: string

                  data:
                    type: object
                    properties:
                      error_message:
                        type: string

                example:
                  status_code: 500
                  message: error
                  data:
                    error_message: Server error

        "404":
          description: No data found for this train
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: integer
                  message:
                    type: string

                  data:
                    type: object
                    properties:
                      error_message:
                        type: string

                example:
                  status_code: 404
                  message: error
                  data:
                    error_message: No data found for this train
